### ISSUE TITLE
Unable to use Supercluster.KDTree with .net framework 4.5 & 4.5.1

### ISSUE THREAD

**Issue by jayasontv** [MathFerret1013/Supercluster.KDTree#1]
When tried to use this with my app(added as a NuGet package), it gives me an error saying - 

> error CS0246: The type or namespace name 'Supercluster' could not be found (are you missing a using directive or an assembly reference?)

This gets resolved when i change my application to target to framework 4.6.1

**Comment by ericreg** [comment]
Will have this fixed by Friday. I will merge the changes made in the Supercluster project KDTree with this and update the documentation. I'll update the Nuget package too.

**Comment by jayasontv** [comment]
Thanks MathFerret1013. Waiting for it.

**Comment by ericreg** [comment]
I have decided not to merge the changes in the main Supercluster project as it would require basically bringing in half of the main project.  I have however fixed the original issue and the project now only depends on .NET 4.5. If you update the nuget reference it should build correctly.  I'm closing the issue. Reopen if you are still having problems.
