### ISSUE TITLE
[Problem] Nearest Mating faces between two List of 3D planar faces using KD Tree

### ISSUE THREAD

**Issue by Naga-Reddy-Vectra** [MathFerret1013/Supercluster.KDTree#7]
**Problem Statement:** 
I have two lists of planar faces of two bodies.

 - List1<Face> {faceA1,faceA2,faceA3,faceA4.....faceAn}
 - List2<Face> {faceB1,faceB2,faceB3,faceB4.....faceBn}

I want to find which two faces in list1 and list2 are touching each other.
say faceA3 - faceB1 are mating / Touching each other. What is the fastest way to find the mating faces?
There is a possibility of finding multiple pairs of mating faces between two lists. 

For Each planar face, I am having a face center (X, Y, Z) and Face normal (Vx, Vy, Vz)

I can create a for each loop run between two lists and compute the distance and get the mating pairs. But as the number of faces increases computation will take more time. 
 
**Note:** 

> Definition of mating faces is Two faces must be at zero distance and
> face normals must be opposite.

**Comment by ericreg** [comment]
Interesting problem Naga, however, I think you have not described an  issue with the library itself. Is there an issue with the library you have found while working on this problem?

**Comment by Naga-Reddy-Vectra** [comment]
Actually frankly speaking I have not used your library for this implementation. I want to know if this library can be solved to find the solution for the problem I have stated. If yes I will go ahead and try to implement it. This is one problem in CAD software where computation time increases. So finding a solution for it. 
If you can help me out in getting an optimal solution using this library, it will be a great solution.

**Comment by ericreg** [comment]
Understood. If you can define a metric and a coordinate space representation, then in theory yes this library would help. I think the difficulty will be **how** the faces may touch. If the mating face centers are always equal (i.e., faceA mates with faceB, if and only if faceA center = faceB center) then the implementation should not be too hard and you should be able to use a standard L2 metric. 

If mating faces may touch at any point in their planes, then the implementation's metric function would be quite different. Keep in my that any metric function you create will need to satisfy the metric space axioms. https://en.wikipedia.org/wiki/Metric_space

**Comment by Naga-Reddy-Vectra** [comment]
FaceA center and FaceB center might not be always the same. But the distance between those two faces will be always ~0.0.

**Comment by ericreg** [comment]
In that case, I'm not sure if this library offers a good solution. There might a some theoretical metric function you could construct to solve this problem using this library but it would likely be very non-intuitive. There may be better approaches using traditional computational geometry or even an optimization approach.

Given that this is not an issue with the library, I am closing this issue.  Please feel free to re open if needed.
